### ISSUE TITLE
Resistor values for R1, R3, R4, R6, R7 missing

### ISSUE THREAD

**Issue by PatrickFranken** [rnplus/ESP8266-relay-board-hardware#1]
I'm currently building this board and some resistor values are missing. Could you provide these?
Missing are the LED current limiting resistors R1, R4, R7 and BC847 resistors R3, R6. For the limiting resistors I calculated 68ohm, is this right? What about the BC847 resistor values?
Thanks!

**Comment by renzenicolai** [comment]
The specific values don't really matter. For switching the NPN transistors (I used MMBT5551 transistors) I use1k resistors because I still had those... a resistor anywhere between 1k and 5k will do the job.

For the leds: resistor value depends on the kind of leds that you use. I used 1k resistors because the leds I use give enough brightness for their application when using that value.

**Comment by PatrickFranken** [comment]
Thanks for the immediate response! I'll use 300 ohms for the LEDs and 2kohms for the transistors.
